#!/bin/bash
set -euo pipefail

cd /data/zhenyangfan/RoboTwin

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
WORKFLOW_ROOT=${WORKFLOW_ROOT:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/formal_failure_workflow}
WORKFLOW_DIR=${WORKFLOW_DIR:-"${WORKFLOW_ROOT}/${TIMESTAMP}"}
STAGE1_CKPT=${STAGE1_CKPT:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/formal_runs/unified_stage1_acthead_open1000_trainable_base/20260330_100537/stage1_epoch_0400.pt}
BASE_ANCHOR_CKPT=${BASE_ANCHOR_CKPT:-${STAGE1_CKPT}}
TRAIN_SCRIPT=${TRAIN_SCRIPT:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/train_stage2_ddp.sh}
WORKFLOW_BIN=/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/run_stage2_failure_workflow.sh

EXPLORE_GPU=${EXPLORE_GPU:-4,5,6,7}
TRAIN_GPU=${TRAIN_GPU:-4,5,6,7}
NPROC_PER_NODE=${NPROC_PER_NODE:-4}
EXPLORE_MASTER_PORT=${EXPLORE_MASTER_PORT:-29621}
TRAIN_MASTER_PORT=${TRAIN_MASTER_PORT:-29631}

USE_WANDB=${USE_WANDB:-false}
NUM_EPOCHS=${NUM_EPOCHS:-250}
BATCH_SIZE=${BATCH_SIZE:-1}
TRAIN_CORRECTION_BATCH_SIZE=${TRAIN_CORRECTION_BATCH_SIZE:-1}
NUM_WORKERS=${NUM_WORKERS:-4}
SAVE_FREQ=${SAVE_FREQ:-25}
MAX_ROLLOUT_STEPS=${MAX_ROLLOUT_STEPS:-1}
RETAIN_WEIGHT=${RETAIN_WEIGHT:-1.0}
RETAIN_WEIGHT_FINAL=${RETAIN_WEIGHT_FINAL:-0.1}
RETAIN_DECAY_START_EPOCH=${RETAIN_DECAY_START_EPOCH:-0}
RETAIN_DECAY_END_EPOCH=${RETAIN_DECAY_END_EPOCH:-100}
RETAIN_DECAY_CURVE=${RETAIN_DECAY_CURVE:-cosine}
FAILURE_EXPLORE_K=${FAILURE_EXPLORE_K:-4}
FAILURE_FAIL_RECOVER_RATE_THRESH=${FAILURE_FAIL_RECOVER_RATE_THRESH:-0.5}
CORRECTION_BUILDER_MODE=${CORRECTION_BUILDER_MODE:-act_aligned}
USE_ACT_HEAD_CORRECTION=${USE_ACT_HEAD_CORRECTION:-true}
DETACH_ACT_FEATURE_FOR_LATENT=${DETACH_ACT_FEATURE_FOR_LATENT:-true}
LAMBDA_WM_ACTION_CURRENT=${LAMBDA_WM_ACTION_CURRENT:-0.0}
LAMBDA_WM_ACTION_FUTURE=${LAMBDA_WM_ACTION_FUTURE:-0.0}
LAMBDA_BRIDGE_FUTURE=${LAMBDA_BRIDGE_FUTURE:-0.0}
DYN_ZERO_STEPS=${DYN_ZERO_STEPS:-0}
DYN_RAMP_STEPS=${DYN_RAMP_STEPS:-100}
DYN_WARMUP_CURVE=${DYN_WARMUP_CURVE:-cosine}
DYN_SCHEDULE_UNIT=${DYN_SCHEDULE_UNIT:-epoch}
REFERENCE_GLOBAL_BATCH_SIZE=${REFERENCE_GLOBAL_BATCH_SIZE:-$(( NPROC_PER_NODE * (BATCH_SIZE + TRAIN_CORRECTION_BATCH_SIZE) ))}
PLANNER_TARGET_LOOKAHEAD_STEPS=${PLANNER_TARGET_LOOKAHEAD_STEPS:-4}
PLANNER_GRIPPER_SWITCH_RATIO=${PLANNER_GRIPPER_SWITCH_RATIO:-0.5}
PLANNER_WARMUP=${PLANNER_WARMUP:-false}
ACT_LIKE_LOSS_ONLY=${ACT_LIKE_LOSS_ONLY:-false}

EVAC_CKPT=${EVAC_CKPT:-/data/zhenyangfan/EVAC/logs/evac_robotwin_finetune_2026-02-07T21-13-51/checkpoints/epoch=2499-step=10000.ckpt}
EVAC_CONFIG=${EVAC_CONFIG:-/data/zhenyangfan/RoboTwin/policy/ACT/evac/configs/robotwin/train_config.yaml}

mkdir -p "${WORKFLOW_DIR}"

if [ ! -f "${STAGE1_CKPT}" ]; then
  echo "[launcher] missing stage1_ckpt=${STAGE1_CKPT}" >&2
  exit 1
fi
if [ ! -f "${EVAC_CKPT}" ]; then
  echo "[launcher] missing evac_ckpt=${EVAC_CKPT}" >&2
  exit 1
fi
if [ ! -f "${EVAC_CONFIG}" ]; then
  echo "[launcher] missing evac_config=${EVAC_CONFIG}" >&2
  exit 1
fi

echo "[launcher] workflow_dir=${WORKFLOW_DIR}"
echo "[launcher] stage1_ckpt=${STAGE1_CKPT}"
echo "[launcher] base_anchor_ckpt=${BASE_ANCHOR_CKPT}"
echo "[launcher] train_script=${TRAIN_SCRIPT}"
echo "[launcher] explore_gpu=${EXPLORE_GPU} train_gpu=${TRAIN_GPU} nproc=${NPROC_PER_NODE}"
echo "[launcher] evac_ckpt=${EVAC_CKPT}"
echo "[launcher] act_like_loss_only=${ACT_LIKE_LOSS_ONLY}"

MODE=explore \
WORKFLOW_DIR="${WORKFLOW_DIR}" \
STAGE1_CKPT="${STAGE1_CKPT}" \
BASE_ANCHOR_CKPT="${BASE_ANCHOR_CKPT}" \
TRAIN_SCRIPT="${TRAIN_SCRIPT}" \
EXPLORE_GPU="${EXPLORE_GPU}" \
TRAIN_GPU="${TRAIN_GPU}" \
NPROC_PER_NODE="${NPROC_PER_NODE}" \
MASTER_PORT="${EXPLORE_MASTER_PORT}" \
USE_WANDB="${USE_WANDB}" \
CORRECTION_BUILDER_MODE="${CORRECTION_BUILDER_MODE}" \
NUM_WORKERS="${NUM_WORKERS}" \
MAX_ROLLOUT_STEPS="${MAX_ROLLOUT_STEPS}" \
FAILURE_EXPLORE_K="${FAILURE_EXPLORE_K}" \
FAILURE_FAIL_RECOVER_RATE_THRESH="${FAILURE_FAIL_RECOVER_RATE_THRESH}" \
EVAC_CKPT="${EVAC_CKPT}" \
EVAC_CONFIG="${EVAC_CONFIG}" \
USE_ACT_HEAD_CORRECTION="${USE_ACT_HEAD_CORRECTION}" \
DETACH_ACT_FEATURE_FOR_LATENT="${DETACH_ACT_FEATURE_FOR_LATENT}" \
LAMBDA_WM_ACTION_CURRENT="${LAMBDA_WM_ACTION_CURRENT}" \
LAMBDA_WM_ACTION_FUTURE="${LAMBDA_WM_ACTION_FUTURE}" \
LAMBDA_BRIDGE_FUTURE="${LAMBDA_BRIDGE_FUTURE}" \
DYN_RAMP_STEPS="${DYN_RAMP_STEPS}" \
DYN_ZERO_STEPS="${DYN_ZERO_STEPS}" \
DYN_WARMUP_CURVE="${DYN_WARMUP_CURVE}" \
DYN_SCHEDULE_UNIT="${DYN_SCHEDULE_UNIT}" \
RETAIN_WEIGHT="${RETAIN_WEIGHT}" \
RETAIN_WEIGHT_FINAL="${RETAIN_WEIGHT_FINAL}" \
RETAIN_DECAY_START_EPOCH="${RETAIN_DECAY_START_EPOCH}" \
RETAIN_DECAY_END_EPOCH="${RETAIN_DECAY_END_EPOCH}" \
RETAIN_DECAY_CURVE="${RETAIN_DECAY_CURVE}" \
REFERENCE_GLOBAL_BATCH_SIZE="${REFERENCE_GLOBAL_BATCH_SIZE}" \
PLANNER_TARGET_LOOKAHEAD_STEPS="${PLANNER_TARGET_LOOKAHEAD_STEPS}" \
PLANNER_GRIPPER_SWITCH_RATIO="${PLANNER_GRIPPER_SWITCH_RATIO}" \
PLANNER_WARMUP="${PLANNER_WARMUP}" \
ACT_LIKE_LOSS_ONLY="${ACT_LIKE_LOSS_ONLY}" \
ACT_ALIGNED_SAMPLE_PREGRASP_PHASE_WINDOW_LEN=20 \
FAILURE_SAMPLE_SKIP_HEAD_RATIO=0.6 \
ACT_ALIGNED_PERTURB_EEF_FAIL_GAIN=0.12 \
ACT_ALIGNED_PERTURB_ROT_MAX_DEG=24 \
FAILURE_TRANSLATION_MAG_BINS=2 \
FAILURE_ROTATION_MAG_BINS=2 \
RECOVER_EVAL_ENABLE=true \
RECOVER_EVAL_SAVE_VIDEO=true \
RECOVER_EVAL_GRIPPER_OPEN_THRESH=0.8 \
RECOVER_EVAL_POS_THRESH_M=0.04 \
RECOVER_EVAL_ROT_THRESH_DEG=8.0 \
RECOVER_EVAL_NEAREST_WINDOW_RADIUS=16 \
PLANNER_ORIENT_WEIGHT=0.0573 \
PLANNER_GRIPPER_PENALTY=1.0 \
"${WORKFLOW_BIN}"

MODE=train \
WORKFLOW_DIR="${WORKFLOW_DIR}" \
STAGE1_CKPT="${STAGE1_CKPT}" \
BASE_ANCHOR_CKPT="${BASE_ANCHOR_CKPT}" \
TRAIN_SCRIPT="${TRAIN_SCRIPT}" \
EXPLORE_GPU="${EXPLORE_GPU}" \
TRAIN_GPU="${TRAIN_GPU}" \
NPROC_PER_NODE="${NPROC_PER_NODE}" \
MASTER_PORT="${TRAIN_MASTER_PORT}" \
USE_WANDB="${USE_WANDB}" \
NUM_EPOCHS="${NUM_EPOCHS}" \
BATCH_SIZE="${BATCH_SIZE}" \
TRAIN_CORRECTION_BATCH_SIZE="${TRAIN_CORRECTION_BATCH_SIZE}" \
NUM_WORKERS="${NUM_WORKERS}" \
SAVE_FREQ="${SAVE_FREQ}" \
CORRECTION_BUILDER_MODE="${CORRECTION_BUILDER_MODE}" \
MAX_ROLLOUT_STEPS="${MAX_ROLLOUT_STEPS}" \
FAILURE_EXPLORE_K="${FAILURE_EXPLORE_K}" \
FAILURE_FAIL_RECOVER_RATE_THRESH="${FAILURE_FAIL_RECOVER_RATE_THRESH}" \
EVAC_CKPT="${EVAC_CKPT}" \
EVAC_CONFIG="${EVAC_CONFIG}" \
USE_ACT_HEAD_CORRECTION="${USE_ACT_HEAD_CORRECTION}" \
DETACH_ACT_FEATURE_FOR_LATENT="${DETACH_ACT_FEATURE_FOR_LATENT}" \
LAMBDA_WM_ACTION_CURRENT="${LAMBDA_WM_ACTION_CURRENT}" \
LAMBDA_WM_ACTION_FUTURE="${LAMBDA_WM_ACTION_FUTURE}" \
LAMBDA_BRIDGE_FUTURE="${LAMBDA_BRIDGE_FUTURE}" \
DYN_RAMP_STEPS="${DYN_RAMP_STEPS}" \
DYN_ZERO_STEPS="${DYN_ZERO_STEPS}" \
DYN_WARMUP_CURVE="${DYN_WARMUP_CURVE}" \
DYN_SCHEDULE_UNIT="${DYN_SCHEDULE_UNIT}" \
RETAIN_WEIGHT="${RETAIN_WEIGHT}" \
RETAIN_WEIGHT_FINAL="${RETAIN_WEIGHT_FINAL}" \
RETAIN_DECAY_START_EPOCH="${RETAIN_DECAY_START_EPOCH}" \
RETAIN_DECAY_END_EPOCH="${RETAIN_DECAY_END_EPOCH}" \
RETAIN_DECAY_CURVE="${RETAIN_DECAY_CURVE}" \
REFERENCE_GLOBAL_BATCH_SIZE="${REFERENCE_GLOBAL_BATCH_SIZE}" \
PLANNER_TARGET_LOOKAHEAD_STEPS="${PLANNER_TARGET_LOOKAHEAD_STEPS}" \
PLANNER_GRIPPER_SWITCH_RATIO="${PLANNER_GRIPPER_SWITCH_RATIO}" \
PLANNER_WARMUP="${PLANNER_WARMUP}" \
ACT_LIKE_LOSS_ONLY="${ACT_LIKE_LOSS_ONLY}" \
ACT_ALIGNED_SAMPLE_PREGRASP_PHASE_WINDOW_LEN=20 \
FAILURE_SAMPLE_SKIP_HEAD_RATIO=0.6 \
ACT_ALIGNED_PERTURB_EEF_FAIL_GAIN=0.12 \
ACT_ALIGNED_PERTURB_ROT_MAX_DEG=24 \
FAILURE_TRANSLATION_MAG_BINS=3 \
FAILURE_ROTATION_MAG_BINS=3 \
RECOVER_EVAL_ENABLE=true \
RECOVER_EVAL_SAVE_VIDEO=false \
RECOVER_EVAL_GRIPPER_OPEN_THRESH=0.8 \
RECOVER_EVAL_POS_THRESH_M=0.04 \
RECOVER_EVAL_ROT_THRESH_DEG=10.0 \
RECOVER_EVAL_NEAREST_WINDOW_RADIUS=16 \
PLANNER_ORIENT_WEIGHT=0.0573 \
PLANNER_GRIPPER_PENALTY=1.0 \
"${WORKFLOW_BIN}"

echo "[launcher] done"
echo "WORKFLOW_DIR=${WORKFLOW_DIR}"
