#!/bin/bash
set -euo pipefail

cd /data/zhenyangfan/RoboTwin

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
RUN_ROOT=${RUN_ROOT:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/formal_runs/stage2_multitask_failure_explore}
RUN_TAG=${RUN_TAG:-stage2_multitask_failure_explore_${TIMESTAMP}}
OUTPUT_DIR=${OUTPUT_DIR:-${RUN_ROOT}/${RUN_TAG}}
LOG_DIR=${LOG_DIR:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/logs}
LOG_FILE=${LOG_FILE:-${LOG_DIR}/${RUN_TAG}.log}
mkdir -p "${OUTPUT_DIR}" "${LOG_DIR}"

STAGE1_CKPT=${STAGE1_CKPT:-/data/zhenyangfan/RoboTwin/policy/ACT/act_ckpt/act-robotwin_multitask_5/demo_clean-50/20260417_002800_robotwin_multitask_5_no_wm/policy_epoch_2000_seed_0.ckpt}
BASE_ANCHOR_CKPT=${BASE_ANCHOR_CKPT:-${STAGE1_CKPT}}
if [ ! -f "${STAGE1_CKPT}" ]; then
  echo "missing STAGE1_CKPT=${STAGE1_CKPT}" >&2
  exit 1
fi

MULTI_TASK_NAMES=${MULTI_TASK_NAMES:-"sim-open_laptop-demo_clean-50 sim-pick_dual_bottles-demo_clean-50 sim-put_bottles_dustbin-demo_clean-50 sim-place_burger_fries-demo_clean-50 sim-handover_block-demo_clean-50"}
GPU_LIST=${GPU_LIST:-0,1,2,3}
NPROC_PER_NODE=${NPROC_PER_NODE:-4}
MASTER_PORT=${MASTER_PORT:-29711}
NUM_EPOCHS=${NUM_EPOCHS:-256}
BATCH_SIZE=${BATCH_SIZE:-4}
NUM_WORKERS=${NUM_WORKERS:-4}
FAILURE_EXPLORE_K=${FAILURE_EXPLORE_K:-4}
FAILURE_SAMPLE_SKIP_HEAD_RATIO=${FAILURE_SAMPLE_SKIP_HEAD_RATIO:-0.6}
FAILURE_TRANSLATION_MAG_BINS=${FAILURE_TRANSLATION_MAG_BINS:-3}
FAILURE_ROTATION_MAG_BINS=${FAILURE_ROTATION_MAG_BINS:-3}
EXPLORE_DEBUG_MAX_SAMPLES=${EXPLORE_DEBUG_MAX_SAMPLES:-2}
EXPLORE_DEBUG_DIR=${EXPLORE_DEBUG_DIR:-${OUTPUT_DIR}/explore_debug}

CUDA_VISIBLE_DEVICES="${GPU_LIST}" \
OUTPUT_DIR="${OUTPUT_DIR}" \
TASK_NAME="robotwin_multitask_stage2" \
MULTI_TASK_NAMES="${MULTI_TASK_NAMES}" \
STAGE1_CKPT="${STAGE1_CKPT}" \
BASE_ANCHOR_CKPT="${BASE_ANCHOR_CKPT}" \
FAILURE_MODE=explore \
CORRECTION_BATCH_SIZE=0 \
CORRECTION_BUILDER_MODE=act_aligned \
USE_ACT_HEAD_CORRECTION=true \
DETACH_ACT_FEATURE_FOR_LATENT=true \
NPROC_PER_NODE="${NPROC_PER_NODE}" \
MASTER_PORT="${MASTER_PORT}" \
NUM_EPOCHS="${NUM_EPOCHS}" \
BATCH_SIZE="${BATCH_SIZE}" \
NUM_WORKERS="${NUM_WORKERS}" \
ACT_CHUNK_SIZE=50 \
PREFIX_STEPS=16 \
FUTURE_OFFSET=16 \
LR=${LR:-3e-5} \
FAILURE_EXPLORE_K="${FAILURE_EXPLORE_K}" \
FAILURE_SAMPLE_SKIP_HEAD_RATIO="${FAILURE_SAMPLE_SKIP_HEAD_RATIO}" \
FAILURE_TRANSLATION_MAG_BINS="${FAILURE_TRANSLATION_MAG_BINS}" \
FAILURE_ROTATION_MAG_BINS="${FAILURE_ROTATION_MAG_BINS}" \
ACT_ALIGNED_SAMPLE_PREGRASP_PHASE_WINDOW_LEN=${ACT_ALIGNED_SAMPLE_PREGRASP_PHASE_WINDOW_LEN:-20} \
ACT_ALIGNED_PERTURB_EEF_FAIL_GAIN=${ACT_ALIGNED_PERTURB_EEF_FAIL_GAIN:-0.12} \
ACT_ALIGNED_PERTURB_ROT_MAX_DEG=${ACT_ALIGNED_PERTURB_ROT_MAX_DEG:-24} \
EXPLORE_DEBUG_MAX_SAMPLES="${EXPLORE_DEBUG_MAX_SAMPLES}" \
EXPLORE_DEBUG_DIR="${EXPLORE_DEBUG_DIR}" \
RECOVER_EVAL_ENABLE=true \
RECOVER_EVAL_SAVE_VIDEO=false \
RECOVER_EVAL_GRIPPER_OPEN_THRESH=${RECOVER_EVAL_GRIPPER_OPEN_THRESH:-0.8} \
RECOVER_EVAL_POS_THRESH_M=${RECOVER_EVAL_POS_THRESH_M:-0.04} \
RECOVER_EVAL_ROT_THRESH_DEG=${RECOVER_EVAL_ROT_THRESH_DEG:-10.0} \
RECOVER_EVAL_NEAREST_WINDOW_RADIUS=${RECOVER_EVAL_NEAREST_WINDOW_RADIUS:-16} \
EVAC_CKPT=${EVAC_CKPT:-/data/yujieyang/EVAC_new/runs/evac_robotwin_new_mixed50p12_plus_pi05_rollout_2026-04-22T17-46-59/checkpoints/epoch=333-step=10000.ckpt} \
EVAC_CONFIG=${EVAC_CONFIG:-/data/yujieyang/EVAC_new/configs/robotwin/train_config_robotwin_new_mixed50p12_plus_pi05_rollout.yaml} \
EVAC_REPO_ROOT=${EVAC_REPO_ROOT:-/data/yujieyang/EVAC_new} \
USE_WANDB=${USE_WANDB:-false} \
WANDB_LOG_MODE=${WANDB_LOG_MODE:-disabled} \
WANDB_RUN_NAME="${RUN_TAG}" \
WANDB_GROUP=stage2_multitask_failure_explore \
/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/train_stage2_ddp.sh \
  2>&1 | tee -a "${LOG_FILE}"

echo "output_dir=${OUTPUT_DIR}"
echo "log_file=${LOG_FILE}"
