#!/bin/bash
set -euo pipefail

cd /data/zhenyangfan/RoboTwin

PYTHON_BIN=${PYTHON_BIN:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/.venv-act-latent/bin/python}
if [ ! -x "${PYTHON_BIN}" ]; then
  echo "python interpreter not found: ${PYTHON_BIN}" >&2
  exit 1
fi
VENV_BIN_DIR=$(dirname "${PYTHON_BIN}")
export PATH="${VENV_BIN_DIR}:${PATH}"

TASK_NAME=${TASK_NAME:-sim-open_laptop-demo_clean-50}
DATASET_DIR=${DATASET_DIR:-}
NUM_EPISODES=${NUM_EPISODES:-}
CAMERA_NAMES=${CAMERA_NAMES:-}
OUTPUT_ROOT=${OUTPUT_ROOT:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/stage2}
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_DIR=${OUTPUT_DIR:-"${OUTPUT_ROOT}/${TIMESTAMP}"}
mkdir -p "${OUTPUT_DIR}"

DEVICE=${DEVICE:-cuda:0}
NUM_EPOCHS=${NUM_EPOCHS:-20}
BATCH_SIZE=${BATCH_SIZE:-1}
CORRECTION_BATCH_SIZE=${CORRECTION_BATCH_SIZE:-0}
NUM_WORKERS=${NUM_WORKERS:-0}
PREFIX_STEPS=${PREFIX_STEPS:-16}
ACT_CHUNK_SIZE=${ACT_CHUNK_SIZE:-50}
FUTURE_OFFSET=${FUTURE_OFFSET:-16}
MAX_STEPS=${MAX_STEPS:--1}
MAX_ROLLOUT_STEPS=${MAX_ROLLOUT_STEPS:-1}
LR=${LR:-3e-5}
WEIGHT_DECAY=${WEIGHT_DECAY:-1e-4}
SAVE_FREQ=${SAVE_FREQ:-5}
DDIM_STEPS=${DDIM_STEPS:-27}
DYN_ZERO_STEPS=${DYN_ZERO_STEPS:-0}
DYN_RAMP_STEPS=${DYN_RAMP_STEPS:-1000}
DYN_WARMUP_CURVE=${DYN_WARMUP_CURVE:-cosine}
DYN_SCHEDULE_UNIT=${DYN_SCHEDULE_UNIT:-step}
REFERENCE_GLOBAL_BATCH_SIZE=${REFERENCE_GLOBAL_BATCH_SIZE:-1}
RETAIN_WEIGHT=${RETAIN_WEIGHT:-0.1}
RETAIN_WEIGHT_FINAL=${RETAIN_WEIGHT_FINAL:-}
RETAIN_DECAY_START_EPOCH=${RETAIN_DECAY_START_EPOCH:--1}
RETAIN_DECAY_END_EPOCH=${RETAIN_DECAY_END_EPOCH:--1}
RETAIN_DECAY_CURVE=${RETAIN_DECAY_CURVE:-linear}
BRIDGE_WEIGHT=${BRIDGE_WEIGHT:-0.0}
FREEZE_BASE_ACT=${FREEZE_BASE_ACT:-false}
DETACH_ACT_FEATURE_FOR_LATENT=${DETACH_ACT_FEATURE_FOR_LATENT:-false}
USE_ACT_HEAD_CORRECTION=${USE_ACT_HEAD_CORRECTION:-false}
RAW_DATA_DIR=${RAW_DATA_DIR:-/data/zhenyangfan/RoboTwin/data/open_laptop/demo_clean/data}
EVAC_CKPT=${EVAC_CKPT:-/data/zhenyangfan/EVAC/logs/evac_robotwin_finetune_2026-02-07T21-13-51/checkpoints/epoch=2499-step=10000.ckpt}
EVAC_CONFIG=${EVAC_CONFIG:-/data/zhenyangfan/EVAC_cache/configs/robotwin/train_config.yaml}
URDF_PATH=${URDF_PATH:-/data/zhenyangfan/RoboTwin/assets/embodiments/aloha-agilex/urdf/arx5_description_isaac.urdf}
CUROBO_LEFT_YML=${CUROBO_LEFT_YML:-/data/zhenyangfan/RoboTwin/assets/embodiments/aloha-agilex/curobo_left.yml}
CUROBO_RIGHT_YML=${CUROBO_RIGHT_YML:-/data/zhenyangfan/RoboTwin/assets/embodiments/aloha-agilex/curobo_right.yml}
LAMBDA_ALIGN=${LAMBDA_ALIGN:-1.0}
BETA_DYNAMICS_MAX=${BETA_DYNAMICS_MAX:-1.0}
LAMBDA_WM_ACTION_CURRENT=${LAMBDA_WM_ACTION_CURRENT:-0.5}
LAMBDA_WM_ACTION_FUTURE=${LAMBDA_WM_ACTION_FUTURE:-1.0}
LAMBDA_BRIDGE_FUTURE=${LAMBDA_BRIDGE_FUTURE:-0.25}
PROJECTOR_MID_CHANNELS=${PROJECTOR_MID_CHANNELS:-256}
WM_ADAPTER_MID_CHANNELS=${WM_ADAPTER_MID_CHANNELS:-128}
READOUT_ADAPTER_MID_CHANNELS=${READOUT_ADAPTER_MID_CHANNELS:-128}
PREDICTOR_NUM_BLOCKS=${PREDICTOR_NUM_BLOCKS:-3}
PLANNER_TARGET_MODE=${PLANNER_TARGET_MODE:-backward}
PLANNER_TARGET_LOOKAHEAD_STEPS=${PLANNER_TARGET_LOOKAHEAD_STEPS:-6}
PLANNER_ORIENT_WEIGHT=${PLANNER_ORIENT_WEIGHT:-0.0573}
PLANNER_GRIPPER_PENALTY=${PLANNER_GRIPPER_PENALTY:-1.0}
PLANNER_NEAREST_WINDOW_RADIUS=${PLANNER_NEAREST_WINDOW_RADIUS:-12}
PLANNER_ACTIVE_JOINT_DELTA_THRESH=${PLANNER_ACTIVE_JOINT_DELTA_THRESH:-0.01}
PLANNER_ACTIVE_GRIPPER_DELTA_THRESH=${PLANNER_ACTIVE_GRIPPER_DELTA_THRESH:-0.05}
PLANNER_GRIPPER_SWITCH_RATIO=${PLANNER_GRIPPER_SWITCH_RATIO:-0.8}
PLANNER_INTERP_FALLBACK=${PLANNER_INTERP_FALLBACK:-true}
PLANNER_WARMUP=${PLANNER_WARMUP:-true}
CORRECTION_INTERP_NEAREST_ENABLE=${CORRECTION_INTERP_NEAREST_ENABLE:-false}
CORRECTION_INTERP_PREFIX_RATIO=${CORRECTION_INTERP_PREFIX_RATIO:-0.4}
CORRECTION_BUILDER_MODE=${CORRECTION_BUILDER_MODE:-legacy}
ACT_ALIGNED_ROLLOUT_EXEC_STEPS=${ACT_ALIGNED_ROLLOUT_EXEC_STEPS:-16}
ACT_ALIGNED_MIN_DIST_FALLBACK_FORCE_CORRECTION=${ACT_ALIGNED_MIN_DIST_FALLBACK_FORCE_CORRECTION:-true}
ACT_ALIGNED_MIN_DIST_RECOVER_RATIO=${ACT_ALIGNED_MIN_DIST_RECOVER_RATIO:-0.75}
ACT_ALIGNED_REAL_ERROR_TRIGGER_ENABLE=${ACT_ALIGNED_REAL_ERROR_TRIGGER_ENABLE:-true}
ACT_ALIGNED_REAL_ERROR_MIN_DIST_THRESH=${ACT_ALIGNED_REAL_ERROR_MIN_DIST_THRESH:-0.01}
ACT_ALIGNED_REAL_ERROR_MIN_DIST_DELTA_THRESH=${ACT_ALIGNED_REAL_ERROR_MIN_DIST_DELTA_THRESH:-0.005}
ACT_ALIGNED_DEBUG_RECOVER_EVAL_ROLLOUT=${ACT_ALIGNED_DEBUG_RECOVER_EVAL_ROLLOUT:-false}
ACT_ALIGNED_DEBUG_CORRECTION_EVAC_ROLLOUT=${ACT_ALIGNED_DEBUG_CORRECTION_EVAC_ROLLOUT:-false}
RECOVER_EVAL_ENABLE=${RECOVER_EVAL_ENABLE:-false}
RECOVER_EVAL_SAVE_VIDEO=${RECOVER_EVAL_SAVE_VIDEO:-false}
RECOVER_EVAL_GRIPPER_OPEN_THRESH=${RECOVER_EVAL_GRIPPER_OPEN_THRESH:-0.8}
RECOVER_EVAL_POS_THRESH_M=${RECOVER_EVAL_POS_THRESH_M:-0.03}
RECOVER_EVAL_ROT_THRESH_DEG=${RECOVER_EVAL_ROT_THRESH_DEG:-10.0}
RECOVER_EVAL_NEAREST_WINDOW_RADIUS=${RECOVER_EVAL_NEAREST_WINDOW_RADIUS:-16}
RECOVER_EVAL_VIDEO_BRIDGE_STEPS=${RECOVER_EVAL_VIDEO_BRIDGE_STEPS:-16}
ACT_ALIGNED_CORRECTION_INTERP_NEAREST_ENABLE=${ACT_ALIGNED_CORRECTION_INTERP_NEAREST_ENABLE:-false}
ACT_ALIGNED_CORRECTION_INTERP_PREFIX_RATIO=${ACT_ALIGNED_CORRECTION_INTERP_PREFIX_RATIO:-0.6}
ACT_ALIGNED_CORRECTION_PLANNER_PREFIX_RATIO=${ACT_ALIGNED_CORRECTION_PLANNER_PREFIX_RATIO:-0.5}
ACT_ALIGNED_CORRECTION_GRIPPER_CLOSE_PREFIX_RATIO=${ACT_ALIGNED_CORRECTION_GRIPPER_CLOSE_PREFIX_RATIO:-0.32}
ACT_ALIGNED_CORRECTION_COMPOSE_GT_TAIL_ENABLE=${ACT_ALIGNED_CORRECTION_COMPOSE_GT_TAIL_ENABLE:-true}
ACT_ALIGNED_CORRECTION_GRIPPER_SWITCH_RATIO=${ACT_ALIGNED_CORRECTION_GRIPPER_SWITCH_RATIO:-0.5}
ACT_ALIGNED_RECOVER_GRIPPER_PENALTY=${ACT_ALIGNED_RECOVER_GRIPPER_PENALTY:-0.0}
ACT_ALIGNED_ENABLE_PERTURB=${ACT_ALIGNED_ENABLE_PERTURB:-true}
ACT_ALIGNED_PERTURB_PROB=${ACT_ALIGNED_PERTURB_PROB:-1.0}
ACT_ALIGNED_PERTURB_ERROR_MODE=${ACT_ALIGNED_PERTURB_ERROR_MODE:-open_laptop_pregrasp}
ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_CLOSE_PROB=${ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_CLOSE_PROB:-0.5}
ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_TRANSLATION_PROB=${ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_TRANSLATION_PROB:-0.0}
ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_ROTATION_PROB=${ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_ROTATION_PROB:-0.0}
ACT_ALIGNED_PERTURB_EEF_FAIL_GAIN=${ACT_ALIGNED_PERTURB_EEF_FAIL_GAIN:-0.10}
ACT_ALIGNED_PERTURB_ROT_MAX_DEG=${ACT_ALIGNED_PERTURB_ROT_MAX_DEG:-15.0}
ACT_ALIGNED_PERTURB_MAG_RANDOM=${ACT_ALIGNED_PERTURB_MAG_RANDOM:-false}
ACT_ALIGNED_PERTURB_MAG_RAND_MIN=${ACT_ALIGNED_PERTURB_MAG_RAND_MIN:-1.0}
ACT_ALIGNED_PERTURB_MAG_RAND_MAX=${ACT_ALIGNED_PERTURB_MAG_RAND_MAX:-1.4}
ACT_ALIGNED_PERTURB_REJECT_SAMPLING_ENABLE=${ACT_ALIGNED_PERTURB_REJECT_SAMPLING_ENABLE:-true}
ACT_ALIGNED_PERTURB_REJECT_MAX_TRIALS=${ACT_ALIGNED_PERTURB_REJECT_MAX_TRIALS:-4}
ACT_ALIGNED_PERTURB_REJECT_DIR_JITTER_EPS=${ACT_ALIGNED_PERTURB_REJECT_DIR_JITTER_EPS:-0.2}
ACT_ALIGNED_PERTURB_GRIPPER_CLOSE_MIN=${ACT_ALIGNED_PERTURB_GRIPPER_CLOSE_MIN:-0.10}
ACT_ALIGNED_PERTURB_GRIPPER_OPEN_MAX=${ACT_ALIGNED_PERTURB_GRIPPER_OPEN_MAX:-0.90}
ACT_ALIGNED_PERTURB_GRIPPER_FAST_RATIO=${ACT_ALIGNED_PERTURB_GRIPPER_FAST_RATIO:-0.20}
ACT_ALIGNED_SAMPLE_PREGRASP_PHASE_WINDOW_LEN=${ACT_ALIGNED_SAMPLE_PREGRASP_PHASE_WINDOW_LEN:-30}
ACT_ALIGNED_ERROR_POLICY_CKPT=${ACT_ALIGNED_ERROR_POLICY_CKPT:-}
ACT_ALIGNED_SAMPLE_TIMEOUT_SEC=${ACT_ALIGNED_SAMPLE_TIMEOUT_SEC:-30}
FAILURE_MODE=${FAILURE_MODE:-off}
FAILURE_TABLE_PATH=${FAILURE_TABLE_PATH:-}
FAILURE_TABLE_DIR=${FAILURE_TABLE_DIR:-}
FAILURE_PHASE_BINS=${FAILURE_PHASE_BINS:-3}
FAILURE_TRANSLATION_DIR_BINS=${FAILURE_TRANSLATION_DIR_BINS:-6}
FAILURE_TRANSLATION_MAG_BINS=${FAILURE_TRANSLATION_MAG_BINS:-3}
FAILURE_ROTATION_DIR_BINS=${FAILURE_ROTATION_DIR_BINS:-6}
FAILURE_ROTATION_MAG_BINS=${FAILURE_ROTATION_MAG_BINS:-3}
FAILURE_EXPLORE_K=${FAILURE_EXPLORE_K:-4}
FAILURE_FAIL_RECOVER_RATE_THRESH=${FAILURE_FAIL_RECOVER_RATE_THRESH:-0.5}
FAILURE_SAMPLE_SKIP_HEAD_RATIO=${FAILURE_SAMPLE_SKIP_HEAD_RATIO:-0.6}
STAGE2_LATENT_CACHE_DIR=${STAGE2_LATENT_CACHE_DIR:-}
STAGE2_LATENT_CACHE_STRICT=${STAGE2_LATENT_CACHE_STRICT:-false}
STAGE2_LATENT_CACHE_WRITEBACK=${STAGE2_LATENT_CACHE_WRITEBACK:-true}
USE_WANDB=${USE_WANDB:-true}
WANDB_PROJECT=${WANDB_PROJECT:-RoboTwin_ACT_LatentCorr}
WANDB_ENTITY=${WANDB_ENTITY:-}
WANDB_RUN_NAME=${WANDB_RUN_NAME:-}
WANDB_GROUP=${WANDB_GROUP:-}
WANDB_LOG_MODE=${WANDB_LOG_MODE:-auto}
RESUME_CKPT=${RESUME_CKPT:-}
OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}
MKL_NUM_THREADS=${MKL_NUM_THREADS:-1}
OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-1}
NUMEXPR_NUM_THREADS=${NUMEXPR_NUM_THREADS:-1}

if [ -z "${WANDB_RUN_NAME}" ]; then
  WANDB_RUN_NAME="stage2_${TIMESTAMP}"
fi

if [ "${WANDB_LOG_MODE}" = "auto" ]; then
  unset WANDB_MODE
else
  export WANDB_MODE="${WANDB_LOG_MODE}"
fi

if [ -z "${STAGE1_CKPT:-}" ]; then
  STAGE1_CKPT=$(ls -1dt /data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/stage1/*/stage1_epoch_*.pt 2>/dev/null | head -n 1 || true)
fi
BASE_ANCHOR_CKPT=${BASE_ANCHOR_CKPT:-}
if [ -z "${STAGE1_CKPT:-}" ]; then
  echo "stage1 checkpoint not found; set STAGE1_CKPT manually" >&2
  exit 1
fi

EXTRA_ARGS=()
if [ -n "${RESUME_CKPT}" ]; then
  EXTRA_ARGS+=(--resume_ckpt "${RESUME_CKPT}")
fi
if [ -n "${BASE_ANCHOR_CKPT}" ]; then
  EXTRA_ARGS+=(--base_anchor_ckpt "${BASE_ANCHOR_CKPT}")
fi
if [ -n "${RETAIN_WEIGHT_FINAL}" ]; then
  EXTRA_ARGS+=(--retain_weight_final "${RETAIN_WEIGHT_FINAL}")
fi
if [ -n "${ACT_ALIGNED_ERROR_POLICY_CKPT}" ]; then
  EXTRA_ARGS+=(--act_aligned_error_policy_ckpt "${ACT_ALIGNED_ERROR_POLICY_CKPT}")
fi
if [ -n "${DATASET_DIR}" ]; then
  EXTRA_ARGS+=(--dataset_dir "${DATASET_DIR}")
fi
if [ -n "${NUM_EPISODES}" ]; then
  EXTRA_ARGS+=(--num_episodes "${NUM_EPISODES}")
fi
if [ -n "${CAMERA_NAMES}" ]; then
  read -r -a CAMERA_NAMES_ARR <<< "${CAMERA_NAMES}"
  EXTRA_ARGS+=(--camera_names "${CAMERA_NAMES_ARR[@]}")
fi
if [ -n "${STAGE2_LATENT_CACHE_DIR}" ]; then
  EXTRA_ARGS+=(--stage2_latent_cache_dir "${STAGE2_LATENT_CACHE_DIR}")
fi

CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0} \
OMP_NUM_THREADS="${OMP_NUM_THREADS}" \
MKL_NUM_THREADS="${MKL_NUM_THREADS}" \
OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS}" \
NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS}" \
PYTHONUNBUFFERED=1 \
"${PYTHON_BIN}" -u -m policy.ACT_LatentCorr.train_stage2_latent \
  --task_name "${TASK_NAME}" \
  --output_dir "${OUTPUT_DIR}" \
  --evac_ckpt "${EVAC_CKPT}" \
  --evac_config "${EVAC_CONFIG}" \
  --raw_data_dir "${RAW_DATA_DIR}" \
  --stage1_ckpt "${STAGE1_CKPT}" \
  --urdf_path "${URDF_PATH}" \
  --curobo_left_yml "${CUROBO_LEFT_YML}" \
  --curobo_right_yml "${CUROBO_RIGHT_YML}" \
  --device "${DEVICE}" \
  --num_epochs "${NUM_EPOCHS}" \
  --max_steps "${MAX_STEPS}" \
  --batch_size "${BATCH_SIZE}" \
  --correction_batch_size "${CORRECTION_BATCH_SIZE}" \
  --num_workers "${NUM_WORKERS}" \
  --lr "${LR}" \
  --weight_decay "${WEIGHT_DECAY}" \
  --save_freq "${SAVE_FREQ}" \
  --prefix_steps "${PREFIX_STEPS}" \
  --act_chunk_size "${ACT_CHUNK_SIZE}" \
  --future_offset "${FUTURE_OFFSET}" \
  --max_rollout_steps "${MAX_ROLLOUT_STEPS}" \
  --lambda_align "${LAMBDA_ALIGN}" \
  --beta_dynamics_max "${BETA_DYNAMICS_MAX}" \
  --lambda_wm_action_current "${LAMBDA_WM_ACTION_CURRENT}" \
  --lambda_wm_action_future "${LAMBDA_WM_ACTION_FUTURE}" \
  --lambda_bridge_future "${LAMBDA_BRIDGE_FUTURE}" \
  --projector_mid_channels "${PROJECTOR_MID_CHANNELS}" \
  --wm_adapter_mid_channels "${WM_ADAPTER_MID_CHANNELS}" \
  --readout_adapter_mid_channels "${READOUT_ADAPTER_MID_CHANNELS}" \
  --predictor_num_blocks "${PREDICTOR_NUM_BLOCKS}" \
  --ddim_steps "${DDIM_STEPS}" \
  --dyn_zero_steps "${DYN_ZERO_STEPS}" \
  --dyn_ramp_steps "${DYN_RAMP_STEPS}" \
  --dyn_warmup_curve "${DYN_WARMUP_CURVE}" \
  --dyn_schedule_unit "${DYN_SCHEDULE_UNIT}" \
  --reference_global_batch_size "${REFERENCE_GLOBAL_BATCH_SIZE}" \
  --retain_weight "${RETAIN_WEIGHT}" \
  --retain_decay_start_epoch "${RETAIN_DECAY_START_EPOCH}" \
  --retain_decay_end_epoch "${RETAIN_DECAY_END_EPOCH}" \
  --retain_decay_curve "${RETAIN_DECAY_CURVE}" \
  --bridge_weight "${BRIDGE_WEIGHT}" \
  --freeze_base_act "${FREEZE_BASE_ACT}" \
  --detach_act_feature_for_latent "${DETACH_ACT_FEATURE_FOR_LATENT}" \
  --use_act_head_correction "${USE_ACT_HEAD_CORRECTION}" \
  --planner_target_mode "${PLANNER_TARGET_MODE}" \
  --planner_target_lookahead_steps "${PLANNER_TARGET_LOOKAHEAD_STEPS}" \
  --planner_orient_weight "${PLANNER_ORIENT_WEIGHT}" \
  --planner_gripper_penalty "${PLANNER_GRIPPER_PENALTY}" \
  --planner_nearest_window_radius "${PLANNER_NEAREST_WINDOW_RADIUS}" \
  --planner_active_joint_delta_thresh "${PLANNER_ACTIVE_JOINT_DELTA_THRESH}" \
  --planner_active_gripper_delta_thresh "${PLANNER_ACTIVE_GRIPPER_DELTA_THRESH}" \
  --planner_gripper_switch_ratio "${PLANNER_GRIPPER_SWITCH_RATIO}" \
  --planner_interp_fallback "${PLANNER_INTERP_FALLBACK}" \
  --planner_warmup "${PLANNER_WARMUP}" \
  --correction_interp_nearest_enable "${CORRECTION_INTERP_NEAREST_ENABLE}" \
  --correction_interp_prefix_ratio "${CORRECTION_INTERP_PREFIX_RATIO}" \
  --correction_builder_mode "${CORRECTION_BUILDER_MODE}" \
  --act_aligned_rollout_exec_steps "${ACT_ALIGNED_ROLLOUT_EXEC_STEPS}" \
  --act_aligned_min_dist_fallback_force_correction "${ACT_ALIGNED_MIN_DIST_FALLBACK_FORCE_CORRECTION}" \
  --act_aligned_min_dist_recover_ratio "${ACT_ALIGNED_MIN_DIST_RECOVER_RATIO}" \
  --act_aligned_real_error_trigger_enable "${ACT_ALIGNED_REAL_ERROR_TRIGGER_ENABLE}" \
  --act_aligned_real_error_min_dist_thresh "${ACT_ALIGNED_REAL_ERROR_MIN_DIST_THRESH}" \
  --act_aligned_real_error_min_dist_delta_thresh "${ACT_ALIGNED_REAL_ERROR_MIN_DIST_DELTA_THRESH}" \
  --act_aligned_debug_recover_eval_rollout "${ACT_ALIGNED_DEBUG_RECOVER_EVAL_ROLLOUT}" \
  --act_aligned_debug_correction_evac_rollout "${ACT_ALIGNED_DEBUG_CORRECTION_EVAC_ROLLOUT}" \
  --recover_eval_enable "${RECOVER_EVAL_ENABLE}" \
  --recover_eval_save_video "${RECOVER_EVAL_SAVE_VIDEO}" \
  --recover_eval_gripper_open_thresh "${RECOVER_EVAL_GRIPPER_OPEN_THRESH}" \
  --recover_eval_pos_thresh_m "${RECOVER_EVAL_POS_THRESH_M}" \
  --recover_eval_rot_thresh_deg "${RECOVER_EVAL_ROT_THRESH_DEG}" \
  --recover_eval_nearest_window_radius "${RECOVER_EVAL_NEAREST_WINDOW_RADIUS}" \
  --recover_eval_video_bridge_steps "${RECOVER_EVAL_VIDEO_BRIDGE_STEPS}" \
  --act_aligned_correction_interp_nearest_enable "${ACT_ALIGNED_CORRECTION_INTERP_NEAREST_ENABLE}" \
  --act_aligned_correction_interp_prefix_ratio "${ACT_ALIGNED_CORRECTION_INTERP_PREFIX_RATIO}" \
  --act_aligned_correction_planner_prefix_ratio "${ACT_ALIGNED_CORRECTION_PLANNER_PREFIX_RATIO}" \
  --act_aligned_correction_gripper_close_prefix_ratio "${ACT_ALIGNED_CORRECTION_GRIPPER_CLOSE_PREFIX_RATIO}" \
  --act_aligned_correction_compose_gt_tail_enable "${ACT_ALIGNED_CORRECTION_COMPOSE_GT_TAIL_ENABLE}" \
  --act_aligned_correction_gripper_switch_ratio "${ACT_ALIGNED_CORRECTION_GRIPPER_SWITCH_RATIO}" \
  --act_aligned_recover_gripper_penalty "${ACT_ALIGNED_RECOVER_GRIPPER_PENALTY}" \
  --act_aligned_enable_perturb "${ACT_ALIGNED_ENABLE_PERTURB}" \
  --act_aligned_perturb_prob "${ACT_ALIGNED_PERTURB_PROB}" \
  --act_aligned_perturb_error_mode "${ACT_ALIGNED_PERTURB_ERROR_MODE}" \
  --act_aligned_perturb_open_laptop_pregrasp_close_prob "${ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_CLOSE_PROB}" \
  --act_aligned_perturb_open_laptop_pregrasp_translation_prob "${ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_TRANSLATION_PROB}" \
  --act_aligned_perturb_open_laptop_pregrasp_rotation_prob "${ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_ROTATION_PROB}" \
  --act_aligned_perturb_eef_fail_gain "${ACT_ALIGNED_PERTURB_EEF_FAIL_GAIN}" \
  --act_aligned_perturb_rot_max_deg "${ACT_ALIGNED_PERTURB_ROT_MAX_DEG}" \
  --act_aligned_perturb_mag_random "${ACT_ALIGNED_PERTURB_MAG_RANDOM}" \
  --act_aligned_perturb_mag_rand_min "${ACT_ALIGNED_PERTURB_MAG_RAND_MIN}" \
  --act_aligned_perturb_mag_rand_max "${ACT_ALIGNED_PERTURB_MAG_RAND_MAX}" \
  --act_aligned_perturb_reject_sampling_enable "${ACT_ALIGNED_PERTURB_REJECT_SAMPLING_ENABLE}" \
  --act_aligned_perturb_reject_max_trials "${ACT_ALIGNED_PERTURB_REJECT_MAX_TRIALS}" \
  --act_aligned_perturb_reject_dir_jitter_eps "${ACT_ALIGNED_PERTURB_REJECT_DIR_JITTER_EPS}" \
  --act_aligned_perturb_gripper_close_min "${ACT_ALIGNED_PERTURB_GRIPPER_CLOSE_MIN}" \
  --act_aligned_perturb_gripper_open_max "${ACT_ALIGNED_PERTURB_GRIPPER_OPEN_MAX}" \
  --act_aligned_perturb_gripper_fast_ratio "${ACT_ALIGNED_PERTURB_GRIPPER_FAST_RATIO}" \
  --act_aligned_sample_pregrasp_phase_window_len "${ACT_ALIGNED_SAMPLE_PREGRASP_PHASE_WINDOW_LEN}" \
  --act_aligned_sample_timeout_sec "${ACT_ALIGNED_SAMPLE_TIMEOUT_SEC}" \
  --failure_mode "${FAILURE_MODE}" \
  --failure_table_path "${FAILURE_TABLE_PATH}" \
  --failure_table_dir "${FAILURE_TABLE_DIR}" \
  --failure_phase_bins "${FAILURE_PHASE_BINS}" \
  --failure_translation_dir_bins "${FAILURE_TRANSLATION_DIR_BINS}" \
  --failure_translation_mag_bins "${FAILURE_TRANSLATION_MAG_BINS}" \
  --failure_rotation_dir_bins "${FAILURE_ROTATION_DIR_BINS}" \
  --failure_rotation_mag_bins "${FAILURE_ROTATION_MAG_BINS}" \
  --failure_explore_k "${FAILURE_EXPLORE_K}" \
  --failure_fail_recover_rate_thresh "${FAILURE_FAIL_RECOVER_RATE_THRESH}" \
  --failure_sample_skip_head_ratio "${FAILURE_SAMPLE_SKIP_HEAD_RATIO}" \
  --stage2_latent_cache_strict "${STAGE2_LATENT_CACHE_STRICT}" \
  --stage2_latent_cache_writeback "${STAGE2_LATENT_CACHE_WRITEBACK}" \
  --use_wandb "${USE_WANDB}" \
  --wandb_project "${WANDB_PROJECT}" \
  --wandb_entity "${WANDB_ENTITY}" \
  --wandb_run_name "${WANDB_RUN_NAME}" \
  --wandb_group "${WANDB_GROUP}" \
  --wandb_mode "${WANDB_LOG_MODE}" \
  "${EXTRA_ARGS[@]}"
