#!/bin/bash
set -euo pipefail

cd /data/zhenyangfan/RoboTwin

RESUME_CKPT=${RESUME_CKPT:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/formal_runs/stage2_from_unified_ep400_actalignedcorr_probe25_free01234567/20260406_205807/stage2_epoch_0015.pt}
STAGE1_CKPT=${STAGE1_CKPT:-}
BASE_ANCHOR_CKPT=${BASE_ANCHOR_CKPT:-${RESUME_CKPT}}
RUN_ROOT=${RUN_ROOT:-/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/formal_runs/stage2_from_ep15_actaligned_triggeronly100_anchor_ep15_free01234567}
RUN_TAG=${RUN_TAG:-stage2_from_ep15_actaligned_triggeronly100_anchor_ep15_free01234567_$(date +"%Y%m%d_%H%M%S")}
LOG_FILE=/data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/logs/${RUN_TAG}.log
TRAIN_SESSION=${TRAIN_SESSION:-stage2_from_ep15_actaligned_triggeronly100_anchor_ep15_free01234567}

mkdir -p "${RUN_ROOT}"
mkdir -p /data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/outputs/logs

if tmux has-session -t "${TRAIN_SESSION}" 2>/dev/null; then
  tmux kill-session -t "${TRAIN_SESSION}"
fi

tmux new-session -d -s "${TRAIN_SESSION}" \
  "CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
   RESUME_CKPT=${RESUME_CKPT} \
   BASE_ANCHOR_CKPT=${BASE_ANCHOR_CKPT} \
   OUTPUT_ROOT=${RUN_ROOT} \
   NPROC_PER_NODE=8 \
   NUM_EPOCHS=100 \
   SAVE_FREQ=25 \
   BATCH_SIZE=1 \
   CORRECTION_BATCH_SIZE=0 \
   LR=3e-5 \
   RETAIN_WEIGHT=1.0 \
   BRIDGE_WEIGHT=0.0 \
   FREEZE_BASE_ACT=false \
   DETACH_ACT_FEATURE_FOR_LATENT=true \
   USE_ACT_HEAD_CORRECTION=true \
   LAMBDA_WM_ACTION_CURRENT=0.0 \
   LAMBDA_WM_ACTION_FUTURE=0.0 \
   LAMBDA_BRIDGE_FUTURE=0.0 \
   DYN_ZERO_STEPS=0 \
   DYN_RAMP_STEPS=200 \
   REFERENCE_GLOBAL_BATCH_SIZE=8 \
   CORRECTION_BUILDER_MODE=act_aligned \
   ACT_ALIGNED_ROLLOUT_EXEC_STEPS=16 \
   ACT_ALIGNED_MIN_DIST_FALLBACK_FORCE_CORRECTION=false \
   ACT_ALIGNED_MIN_DIST_RECOVER_RATIO=0.75 \
   ACT_ALIGNED_REAL_ERROR_TRIGGER_ENABLE=true \
   ACT_ALIGNED_REAL_ERROR_MIN_DIST_THRESH=0.01 \
   ACT_ALIGNED_REAL_ERROR_MIN_DIST_DELTA_THRESH=0.005 \
   ACT_ALIGNED_DEBUG_RECOVER_EVAL_ROLLOUT=false \
   ACT_ALIGNED_DEBUG_CORRECTION_EVAC_ROLLOUT=false \
   ACT_ALIGNED_CORRECTION_INTERP_NEAREST_ENABLE=false \
   ACT_ALIGNED_CORRECTION_INTERP_PREFIX_RATIO=0.6 \
   ACT_ALIGNED_CORRECTION_PLANNER_PREFIX_RATIO=0.5 \
   ACT_ALIGNED_CORRECTION_GRIPPER_CLOSE_PREFIX_RATIO=0.32 \
   ACT_ALIGNED_CORRECTION_COMPOSE_GT_TAIL_ENABLE=true \
   ACT_ALIGNED_CORRECTION_GRIPPER_SWITCH_RATIO=0.5 \
   ACT_ALIGNED_RECOVER_GRIPPER_PENALTY=0.0 \
   ACT_ALIGNED_ENABLE_PERTURB=false \
   ACT_ALIGNED_PERTURB_PROB=0.0 \
   ACT_ALIGNED_PERTURB_ERROR_MODE=open_laptop_pregrasp \
   ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_CLOSE_PROB=0.5 \
   ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_TRANSLATION_PROB=0.0 \
   ACT_ALIGNED_PERTURB_OPEN_LAPTOP_PREGRASP_ROTATION_PROB=0.0 \
   ACT_ALIGNED_PERTURB_EEF_FAIL_GAIN=0.10 \
   ACT_ALIGNED_PERTURB_ROT_MAX_DEG=15.0 \
   ACT_ALIGNED_PERTURB_MAG_RANDOM=false \
   ACT_ALIGNED_PERTURB_MAG_RAND_MIN=1.0 \
   ACT_ALIGNED_PERTURB_MAG_RAND_MAX=1.4 \
   ACT_ALIGNED_PERTURB_REJECT_SAMPLING_ENABLE=true \
   ACT_ALIGNED_PERTURB_REJECT_MAX_TRIALS=4 \
   ACT_ALIGNED_PERTURB_REJECT_DIR_JITTER_EPS=0.2 \
   ACT_ALIGNED_PERTURB_GRIPPER_CLOSE_MIN=0.10 \
   ACT_ALIGNED_PERTURB_GRIPPER_OPEN_MAX=0.90 \
   ACT_ALIGNED_PERTURB_GRIPPER_FAST_RATIO=0.20 \
   ACT_ALIGNED_SAMPLE_PREGRASP_PHASE_WINDOW_LEN=30 \
   ACT_ALIGNED_SAMPLE_TIMEOUT_SEC=20 \
   PLANNER_TARGET_MODE=backward \
   PLANNER_TARGET_LOOKAHEAD_STEPS=4 \
   PLANNER_ORIENT_WEIGHT=0.0573 \
   PLANNER_GRIPPER_PENALTY=1.0 \
   PLANNER_NEAREST_WINDOW_RADIUS=12 \
   PLANNER_ACTIVE_JOINT_DELTA_THRESH=0.01 \
   PLANNER_ACTIVE_GRIPPER_DELTA_THRESH=0.05 \
   PLANNER_GRIPPER_SWITCH_RATIO=0.8 \
   PLANNER_INTERP_FALLBACK=true \
   PLANNER_WARMUP=false \
   TORCH_DISTRIBUTED_TIMEOUT_MIN=120 \
   TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=7200 \
   WANDB_RUN_NAME=${RUN_TAG} \
   WANDB_GROUP=stage2_from_ep15_actaligned_triggeronly100_anchor_ep15_free01234567 \
   /data/zhenyangfan/RoboTwin/policy/ACT_LatentCorr/train_stage2_ddp.sh > ${LOG_FILE} 2>&1"

TARGET_DIR=""
for _ in $(seq 1 20); do
  TARGET_DIR=$(find "${RUN_ROOT}" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort | tail -n 1)
  [ -n "${TARGET_DIR}" ] && break
  sleep 3
done

if [ -z "${TARGET_DIR}" ]; then
  echo "failed to resolve target output directory under ${RUN_ROOT}" >&2
  exit 1
fi

echo "train_session=${TRAIN_SESSION}"
echo "log_file=${LOG_FILE}"
echo "output_dir=${TARGET_DIR}"
